name: Sumo_reloaded
main: sumo.Sumo
softdepend: [WorldEdit, Vault, HeadsPlus, mcMMO, PlaceholderAPI, Parties]
version: ${project.version}
api-version: 1.21.3
author: steve4744
commands:
  sumosetup:
    description: Sumo arena setup commands
    aliases: smsetup
  sumo:
    description: Sumo_reloaded game commands
    aliases: sm
  sumoconsole:
    description: Sumo console commands
    aliases: smconsole
permissions:
  sumo.join:
    description: used to control who can play Sumo and where
    default: true
  sumo.autojoin:
    description: used to control who can use the autojoin command
    default: true
  sumo.setup:
    description: used to create and modify arenas and gameplay
    default: op
  sumo.version.check:
    description: display new version message on player join
    default: op
  sumo.heads:
    description: control who can use HeadsPlus in-game
    default: true
  sumo.shop:
    description: allow players to buy any shop item (if they have money)
    default: true
  sumo.joinmenu:
    description: allow players to use the join menu
    default: true
  sumo.start:
    description: allow players to start an arena before the minimum players is reached
    default: op
  sumo.spectate:
    description: allow players to join the arena as a spectator
    default: op
  sumo.listrewards:
    description: allow players to list the arena rewards
    default: true
  sumo.party:
    description: allow players to create and join Sumo parties
    default: true
libraries:
  - org.apache.commons:commons-lang3:3.12.0